# Generated by Django 4.2.13 on 2024-06-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="like_count",
            field=models.IntegerField(),
        ),
    ]
