# Generated by Django 4.2.13 on 2024-07-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_feed_like_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("is_marked", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("is_like", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_id", models.IntegerField(default=0)),
                ("email", models.EmailField(default="", max_length=254)),
                ("reply_content", models.TextField()),
            ],
        ),
    ]
