# Generated by Django 4.2.13 on 2024-07-03 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_bookmark_like_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="like_count",
        ),
    ]
